version: "3.9"

services:
  sd-generator:
    build:
      context: ./sd-generator
      dockerfile: Dockerfile
    env_file: ./sd-generator/.env
    ports:
      - ${GENERATOR_HTTP_PORT:-4000}:${GENERATOR_HTTP_PORT:-4000}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - users:/users
      - stable-diffusion-v1-4:/stable-diffusion-v1-4
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - ${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}
    volumes:
      - users:/app/users
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./frontend/.env
    ports:
      - ${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}
    restart: always

volumes:
  users:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/users
  stable-diffusion-v1-4:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/../stable-diffusion-v1-4
