import dotenv from 'dotenv'
dotenv.config()

export const LOG_LEVEL = process.env.LOG_LEVEL ?? 'info'
export const PORT = process.env.PORT ?? '8000'
export const CMC_KEY = process.env.CMC_KEY ?? ''
export const OPENAI_API_KEY = process.env.OPENAI_API_KEY ?? ''
export const OPENAI_API_URL = process.env.OPENAI_API_URL ?? 'https://api.openai.com/v1/'
export const STABLE_DIFFUSION_API_KEY = process.env.STABLE_DIFFUSION_API_KEY ?? ''
export const STABLE_DIFFUSION_API_URL = process.env.STABLE_DIFFUSION_API_URL ?? ''
export const DATABASE_URL = process.env.DATABASE_URL ?? ''
export const TZ = process.env.TZ ?? ''
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID ?? ''
export const DISCORD_CLIENT_ID = process.env.DISCORD_CLIENT_ID ?? ''
export const DISCORD_CLIENT_SECRET = process.env.DISCORD_CLIENT_SECRET ?? ''
export const APP_URL = process.env.APP_URL ?? ''
export const USER_DIR_PWD = process.env.USER_DIR_PWD ?? ''
export const REQUIRE_AUTH = process.env.REQUIRE_AUTH ?? 'true'
export const MOCK_GPT = process.env.MOCK_GPT ?? 'false'
export const MOCK_GPT_GEN_S = process.env.MOCK_GPT_GEN_S ?? '2'
export const BLOCKED_LIST_CHECK_INTERVAL_MS = process.env.BLOCKED_LIST_CHECK_INTERVAL_MS ?? '1000'
